export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — nothing generic.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top — making your learning more organized.",
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];

export const CARD_BG = [
  { id: 3, bgcolor: "linear-gradient(135deg, #e4f2ff 0%, #f3feff 100%)" }, // sky ice
  { id: 4, bgcolor: "linear-gradient(135deg, #f3ecff 0%, #faf7ff 100%)" }, // lilac haze
  { id: 5, bgcolor: "linear-gradient(135deg, #ffeef8 0%, #fff6fb 100%)" }, // rose quartz
  { id: 6, bgcolor: "linear-gradient(135deg, #eaffe7 0%, #f5fff3 100%)" }, // mint cream
  { id: 7, bgcolor: "linear-gradient(135deg, #fff6e6 0%, #fffaf1 100%)" }, // soft apricot
  { id: 10, bgcolor: "linear-gradient(135deg, #e7ecff 0%, #ebf2ff 100%)" }, // gentle lavender-blue
];
